import type { Metadata } from 'next';
import { Playfair_Display, Proza_Libre } from 'next/font/google';

import './globals.css';
import ThemeProvider from './theme/theme-provider';

const playfair_display = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
});

const proza_libre = Proza_Libre({
  variable: '--font-proza-libre',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfair_display.variable} ${proza_libre.variable} antialiased bg-emerald-300 dark:bg-black mood:bg-green-500`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="mood"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
