import type { Metadata } from 'next';
import { Playfair_Display, Proza_Libre, Parisienne } from 'next/font/google';

import './globals.css';
import ThemeProvider from './theme/theme-provider';

const playfair_display = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
});

const parisienne = Parisienne({
  variable: '--parisienne',
  weight: ['400'],
  subsets: ['latin'],
});

const proza_libre = Proza_Libre({
  variable: '--font-proza-libre',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const light = 'bg-[#F1EFE3] text-[#2A353D]';
const dark = 'dark:bg-[#2F4157] dark:text-[#FFFFFF]';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfair_display.variable} ${proza_libre.variable} ${parisienne.variable} antialiased  ${light} ${dark}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
